version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
