services:
  app:
    build: ./docker/app
    volumes:
      - ./:/var/www/html
    # depends_on:
    #   - db

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

#   db:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_DB: laravel
#       POSTGRES_USER: laravel
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "5432:5433"
#     volumes:
#       - db-data:/var/lib/postgresql/data


# volumes:
#   db-data:
