services:
  app:
    build:
      context: .          # 👈 raíz del proyecto Laravel
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cached
    networks:
      - laravel

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # servicio rabbit
      - "15672:15672"   # panel web
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
